# Generated by Django 5.0.4 on 2024-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_qism_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
